// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN1Bpej2ZdH1T0LsUBJTIVO9Skc1lVHEQ',
    appId: '1:861084645325:web:0d71851c44ca8f76dc3684',
    messagingSenderId: '861084645325',
    projectId: 'assesment-1e03f',
    authDomain: 'assesment-1e03f.firebaseapp.com',
    storageBucket: 'assesment-1e03f.firebasestorage.app',
    measurementId: 'G-8Q0TSW01CB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8HRgtm05nCqrsHhlueymRaa2vl4QKpSc',
    appId: '1:861084645325:android:4f832138f00830c4dc3684',
    messagingSenderId: '861084645325',
    projectId: 'assesment-1e03f',
    storageBucket: 'assesment-1e03f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgGe2jbNmkiOreH39rkhJvZtZkI4Kia_8',
    appId: '1:861084645325:ios:ae0bf5f4661a55bfdc3684',
    messagingSenderId: '861084645325',
    projectId: 'assesment-1e03f',
    storageBucket: 'assesment-1e03f.firebasestorage.app',
    iosBundleId: 'com.example.assesment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgGe2jbNmkiOreH39rkhJvZtZkI4Kia_8',
    appId: '1:861084645325:ios:ae0bf5f4661a55bfdc3684',
    messagingSenderId: '861084645325',
    projectId: 'assesment-1e03f',
    storageBucket: 'assesment-1e03f.firebasestorage.app',
    iosBundleId: 'com.example.assesment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN1Bpej2ZdH1T0LsUBJTIVO9Skc1lVHEQ',
    appId: '1:861084645325:web:8f5366a059cdf4b9dc3684',
    messagingSenderId: '861084645325',
    projectId: 'assesment-1e03f',
    authDomain: 'assesment-1e03f.firebaseapp.com',
    storageBucket: 'assesment-1e03f.firebasestorage.app',
    measurementId: 'G-9TCTLBNK6K',
  );
}
